# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5eacb9677bfda61b9b51829fc46dac562860d2f31ccf99b99bac43c1fee00ef16bfd6c348094bd392e02fc3e142c9debaab42cd36630f897d5d7e4215700c2f3

test:
  secret_key_base: a428012dd84da1358876646950ded54d87676eedd77f9450bebd8542f509ebdb4e12f310d8100efdfef92dc7ec1fc2c2e2557f6923f1d0f3319fd2569e419ac9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
